/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Ultra Sim
         * @description Kicks off the sim loop as a background task and returns immediately — the sim never
         *     waits for callers any more than it waits for the LLM. Only one run at a time in v1
         *     (single-runner, no race-end concept yet, per CLAUDE.md). duration_min defaults to the full
         *     60h race; pass a smaller value for a bounded live canary.
         */
        post: operations["run_ultra_sim_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Geometry
         * @description Static course shape for the frontend map — trail polyline + book locations. Not part
         *     of the WS stream: sim.course.load_course() is lru_cached and doesn't change mid-race, so
         *     the frontend fetches this once rather than getting it re-broadcast every tick.
         */
        get: operations["course_geometry_course_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schema Export
         * @description Schema-export-only — never actually returns 200. FastAPI doesn't document WebSocket
         *     payloads in /openapi.json at all, and RaceState only ever flows over /ws, so without this
         *     route openapi-typescript would generate nothing for it (ADR-0011/CLAUDE.md's Type sync
         *     note: never hand-write duplicate TS types). `response_model=RaceState` is what puts its
         *     schema into /openapi.json's components — the handler itself is never meant to succeed.
         *     `model` is a query param (not a path segment) so future WS-only models can reuse this
         *     same route instead of getting one route each.
         */
        get: operations["schema_export_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CourseBook */
        CourseBook: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * CourseGeometry
         * @description The static course shape (trail polyline + book locations) for the frontend map. Never
         *     broadcast over /ws — fetched once via GET /course, since sim.course.load_course() is
         *     lru_cached and doesn't change mid-race.
         */
        CourseGeometry: {
            /** Points */
            points: [
                number,
                number
            ][];
            /** Books */
            books: components["schemas"]["CourseBook"][];
        };
        /** Decision */
        Decision: {
            /** Effort */
            effort: number;
            /** Eat */
            eat: boolean;
            /** Drink */
            drink: boolean;
            /** Bearing Deg */
            bearing_deg: number;
            /** Rest Min */
            rest_min: number;
            /** Quit */
            quit: boolean;
            /** Monologue */
            monologue: string;
        };
        /** FrozenHeadStatePark */
        FrozenHeadStatePark: {
            /** Elapsed Min */
            elapsed_min: number;
            /** Weather */
            weather: string;
            /** Temperature C */
            temperature_c: number;
            /** Is Daylight */
            is_daylight: boolean;
            /** Fog Pct */
            fog_pct: number;
            /** Heat Index */
            heat_index: number;
            /** Local Time */
            local_time: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PhysiologyState */
        PhysiologyState: {
            /** Elapsed Min */
            elapsed_min: number;
            /** Hr */
            hr: number;
            /** Glycogen Pct */
            glycogen_pct: number;
            /** Hydration Pct */
            hydration_pct: number;
            /** Core Temp C */
            core_temp_c: number;
            /** Start Core Temp C */
            start_core_temp_c: number;
            /** Bonk Push Min */
            bonk_push_min: number;
        };
        /**
         * RaceState
         * @description The full broadcast snapshot: sim clock, environment, every runner.
         *     Named RaceState (not WorldState) to avoid colliding with FrozenHeadStatePark,
         *     which owns the weather/environment data this model embeds.
         */
        RaceState: {
            /** Elapsed Min */
            elapsed_min: number;
            environment: components["schemas"]["FrozenHeadStatePark"];
            /** Runners */
            runners: {
                [key: string]: components["schemas"]["RunnerState"];
            };
        };
        /**
         * RunnerState
         * @description Everything about one runner, broadcast/logged as-is. Wraps PhysiologyState
         *     rather than re-declaring its fields.
         */
        RunnerState: {
            /** Persona Name */
            persona_name: string;
            /** Bib Number */
            bib_number: number;
            physiology: components["schemas"]["PhysiologyState"];
            /** True Pos */
            true_pos: [
                number,
                number
            ];
            /** Current Terrain */
            current_terrain: string;
            /** Believed Pos */
            believed_pos: [
                number,
                number
            ];
            /** Loop */
            loop: number;
            /** Books Found */
            books_found: number;
            /** Pace Min Per Km */
            pace_min_per_km: number;
            /** Feel */
            feel: string;
            last_decision?: components["schemas"]["Decision"] | null;
            /** Last Event */
            last_event?: ("found_book" | "tripped_and_fell" | "stepped_in_puddle" | "briar_scratch" | "spooked_by_wildlife" | "dropped_water_bottle") | null;
            /** Last Hallucination */
            last_hallucination?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_ultra_sim_run_post: {
        parameters: {
            query?: {
                speed?: number;
                duration_min?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_geometry_course_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseGeometry"];
                };
            };
        };
    };
    schema_export_schema_get: {
        parameters: {
            query: {
                model: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
